set_property MARK_DEBUG true [get_nets clk_gtu_i]
set_property MARK_DEBUG true [get_nets clk_40MHZ_p_i]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_right_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {ec_transmit_on_left_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[27]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[45]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[29]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[47]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[43]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[39]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[30]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[32]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[33]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[35]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[40]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[37]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[8]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[26]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[6]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[22]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[18]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[20]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[9]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[11]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[13]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[15]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[37]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[29]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[31]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[33]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[35]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[39]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[41]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[43]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[47]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[45]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[7]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[6]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[8]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[9]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[10]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[11]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[12]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[13]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[14]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[15]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[16]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[18]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[20]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[22]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[24]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[26]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[28]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[27]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[25]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[23]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[21]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[19]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[17]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[44]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[38]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[31]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[46]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[41]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[34]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[42]}]
set_property MARK_DEBUG true [get_nets {ec_data_right_IBUF[36]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[7]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[10]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[12]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[14]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[16]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[17]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[19]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[21]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[23]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[24]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[25]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[32]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[28]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[30]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[34]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[36]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[38]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[40]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[42]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[44]}]
set_property MARK_DEBUG true [get_nets {ec_data_left_IBUF[46]}]

set_property MARK_DEBUG true [get_nets acq_on_sync]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[4]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[2]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[0]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[1]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[3]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[5]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[6]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[12]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[14]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[20]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[22]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[28]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[30]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[31]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[29]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[23]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[21]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[26]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[27]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[24]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[25]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[15]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[13]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[18]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[19]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[16]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[17]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[7]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[8]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[9]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[10]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[11]}]

set_property MARK_DEBUG false [get_nets readout_dataout_left_dv_0]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[2].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[0].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[3].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[5].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[4].inst_pmt_readout_left/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[5].inst_pmt_readout_right/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[3].inst_pmt_readout_right/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_right/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[2].inst_pmt_readout_right/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[4].inst_pmt_readout_right/dataout_dv}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[0].inst_pmt_readout_right/dataout_dv}]


set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[0]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[1]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[2]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[3]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[4]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[5]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[0]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[1]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[2]}]
set_property MARK_DEBUG true [get_nets {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[3]}]

set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[12]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[4]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[0]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[1]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[2]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[3]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[5]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[6]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[7]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[8]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[14]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[15]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[13]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[18]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[19]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[16]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[17]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[22]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[23]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[20]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[21]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[26]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[27]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[24]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[25]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[30]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[31]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[28]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[29]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[34]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[35]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[32]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[33]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[38]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[39]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[36]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[37]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[42]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[43]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[40]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[41]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[46]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[47]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[44]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[45]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[9]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[10]}]
set_property MARK_DEBUG true [get_nets {m_axis_tdata_left_hf[11]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[0]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[1]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[2]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[3]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[4]}]
set_property MARK_DEBUG true [get_nets {m_axis_tvalid_left_hf[5]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_clk_ec_gen/inst/clk_ec]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ec_transmit_on_left_IBUF[0]} {ec_transmit_on_left_IBUF[1]} {ec_transmit_on_left_IBUF[2]} {ec_transmit_on_left_IBUF[3]} {ec_transmit_on_left_IBUF[4]} {ec_transmit_on_left_IBUF[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ec_transmit_on_right_IBUF[0]} {ec_transmit_on_right_IBUF[1]} {ec_transmit_on_right_IBUF[2]} {ec_transmit_on_right_IBUF[3]} {ec_transmit_on_right_IBUF[4]} {ec_transmit_on_right_IBUF[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 48 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ec_data_right_IBUF[0]} {ec_data_right_IBUF[1]} {ec_data_right_IBUF[2]} {ec_data_right_IBUF[3]} {ec_data_right_IBUF[4]} {ec_data_right_IBUF[5]} {ec_data_right_IBUF[6]} {ec_data_right_IBUF[7]} {ec_data_right_IBUF[8]} {ec_data_right_IBUF[9]} {ec_data_right_IBUF[10]} {ec_data_right_IBUF[11]} {ec_data_right_IBUF[12]} {ec_data_right_IBUF[13]} {ec_data_right_IBUF[14]} {ec_data_right_IBUF[15]} {ec_data_right_IBUF[16]} {ec_data_right_IBUF[17]} {ec_data_right_IBUF[18]} {ec_data_right_IBUF[19]} {ec_data_right_IBUF[20]} {ec_data_right_IBUF[21]} {ec_data_right_IBUF[22]} {ec_data_right_IBUF[23]} {ec_data_right_IBUF[24]} {ec_data_right_IBUF[25]} {ec_data_right_IBUF[26]} {ec_data_right_IBUF[27]} {ec_data_right_IBUF[28]} {ec_data_right_IBUF[29]} {ec_data_right_IBUF[30]} {ec_data_right_IBUF[31]} {ec_data_right_IBUF[32]} {ec_data_right_IBUF[33]} {ec_data_right_IBUF[34]} {ec_data_right_IBUF[35]} {ec_data_right_IBUF[36]} {ec_data_right_IBUF[37]} {ec_data_right_IBUF[38]} {ec_data_right_IBUF[39]} {ec_data_right_IBUF[40]} {ec_data_right_IBUF[41]} {ec_data_right_IBUF[42]} {ec_data_right_IBUF[43]} {ec_data_right_IBUF[44]} {ec_data_right_IBUF[45]} {ec_data_right_IBUF[46]} {ec_data_right_IBUF[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 48 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ec_data_left_IBUF[0]} {ec_data_left_IBUF[1]} {ec_data_left_IBUF[2]} {ec_data_left_IBUF[3]} {ec_data_left_IBUF[4]} {ec_data_left_IBUF[5]} {ec_data_left_IBUF[6]} {ec_data_left_IBUF[7]} {ec_data_left_IBUF[8]} {ec_data_left_IBUF[9]} {ec_data_left_IBUF[10]} {ec_data_left_IBUF[11]} {ec_data_left_IBUF[12]} {ec_data_left_IBUF[13]} {ec_data_left_IBUF[14]} {ec_data_left_IBUF[15]} {ec_data_left_IBUF[16]} {ec_data_left_IBUF[17]} {ec_data_left_IBUF[18]} {ec_data_left_IBUF[19]} {ec_data_left_IBUF[20]} {ec_data_left_IBUF[21]} {ec_data_left_IBUF[22]} {ec_data_left_IBUF[23]} {ec_data_left_IBUF[24]} {ec_data_left_IBUF[25]} {ec_data_left_IBUF[26]} {ec_data_left_IBUF[27]} {ec_data_left_IBUF[28]} {ec_data_left_IBUF[29]} {ec_data_left_IBUF[30]} {ec_data_left_IBUF[31]} {ec_data_left_IBUF[32]} {ec_data_left_IBUF[33]} {ec_data_left_IBUF[34]} {ec_data_left_IBUF[35]} {ec_data_left_IBUF[36]} {ec_data_left_IBUF[37]} {ec_data_left_IBUF[38]} {ec_data_left_IBUF[39]} {ec_data_left_IBUF[40]} {ec_data_left_IBUF[41]} {ec_data_left_IBUF[42]} {ec_data_left_IBUF[43]} {ec_data_left_IBUF[44]} {ec_data_left_IBUF[45]} {ec_data_left_IBUF[46]} {ec_data_left_IBUF[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 6 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[0]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[1]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[2]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[3]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[4]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_bit_counter[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[0]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[1]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[2]} {gen_inst_pmt_readout[1].inst_pmt_readout_left/readout_process_state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list acq_on_sync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list clk_40MHZ_p_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list clk_gtu_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {gen_inst_pmt_readout[0].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {gen_inst_pmt_readout[3].inst_pmt_readout_right/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {gen_inst_pmt_readout[4].inst_pmt_readout_right/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {gen_inst_pmt_readout[5].inst_pmt_readout_right/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {gen_inst_pmt_readout[0].inst_pmt_readout_right/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {gen_inst_pmt_readout[5].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {gen_inst_pmt_readout[3].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {gen_inst_pmt_readout[2].inst_pmt_readout_right/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {gen_inst_pmt_readout[4].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {gen_inst_pmt_readout[2].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {gen_inst_pmt_readout[1].inst_pmt_readout_left/dataout_dv}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {gen_inst_pmt_readout[1].inst_pmt_readout_right/dataout_dv}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list i_clk_ec_gen/inst/clk_hf]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 48 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {m_axis_tdata_left_hf[0]} {m_axis_tdata_left_hf[1]} {m_axis_tdata_left_hf[2]} {m_axis_tdata_left_hf[3]} {m_axis_tdata_left_hf[4]} {m_axis_tdata_left_hf[5]} {m_axis_tdata_left_hf[6]} {m_axis_tdata_left_hf[7]} {m_axis_tdata_left_hf[8]} {m_axis_tdata_left_hf[9]} {m_axis_tdata_left_hf[10]} {m_axis_tdata_left_hf[11]} {m_axis_tdata_left_hf[12]} {m_axis_tdata_left_hf[13]} {m_axis_tdata_left_hf[14]} {m_axis_tdata_left_hf[15]} {m_axis_tdata_left_hf[16]} {m_axis_tdata_left_hf[17]} {m_axis_tdata_left_hf[18]} {m_axis_tdata_left_hf[19]} {m_axis_tdata_left_hf[20]} {m_axis_tdata_left_hf[21]} {m_axis_tdata_left_hf[22]} {m_axis_tdata_left_hf[23]} {m_axis_tdata_left_hf[24]} {m_axis_tdata_left_hf[25]} {m_axis_tdata_left_hf[26]} {m_axis_tdata_left_hf[27]} {m_axis_tdata_left_hf[28]} {m_axis_tdata_left_hf[29]} {m_axis_tdata_left_hf[30]} {m_axis_tdata_left_hf[31]} {m_axis_tdata_left_hf[32]} {m_axis_tdata_left_hf[33]} {m_axis_tdata_left_hf[34]} {m_axis_tdata_left_hf[35]} {m_axis_tdata_left_hf[36]} {m_axis_tdata_left_hf[37]} {m_axis_tdata_left_hf[38]} {m_axis_tdata_left_hf[39]} {m_axis_tdata_left_hf[40]} {m_axis_tdata_left_hf[41]} {m_axis_tdata_left_hf[42]} {m_axis_tdata_left_hf[43]} {m_axis_tdata_left_hf[44]} {m_axis_tdata_left_hf[45]} {m_axis_tdata_left_hf[46]} {m_axis_tdata_left_hf[47]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 6 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {m_axis_tvalid_left_hf[0]} {m_axis_tvalid_left_hf[1]} {m_axis_tvalid_left_hf[2]} {m_axis_tvalid_left_hf[3]} {m_axis_tvalid_left_hf[4]} {m_axis_tvalid_left_hf[5]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list i_clk_wiz/inst/clk_200MHz]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 32 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {i_sc/sreg_input_reg[0]} {i_sc/sreg_input_reg[1]} {i_sc/sreg_input_reg[2]} {i_sc/sreg_input_reg[3]} {i_sc/sreg_input_reg[4]} {i_sc/sreg_input_reg[5]} {i_sc/sreg_input_reg[6]} {i_sc/sreg_input_reg[7]} {i_sc/sreg_input_reg[8]} {i_sc/sreg_input_reg[9]} {i_sc/sreg_input_reg[10]} {i_sc/sreg_input_reg[11]} {i_sc/sreg_input_reg[12]} {i_sc/sreg_input_reg[13]} {i_sc/sreg_input_reg[14]} {i_sc/sreg_input_reg[15]} {i_sc/sreg_input_reg[16]} {i_sc/sreg_input_reg[17]} {i_sc/sreg_input_reg[18]} {i_sc/sreg_input_reg[19]} {i_sc/sreg_input_reg[20]} {i_sc/sreg_input_reg[21]} {i_sc/sreg_input_reg[22]} {i_sc/sreg_input_reg[23]} {i_sc/sreg_input_reg[24]} {i_sc/sreg_input_reg[25]} {i_sc/sreg_input_reg[26]} {i_sc/sreg_input_reg[27]} {i_sc/sreg_input_reg[28]} {i_sc/sreg_input_reg[29]} {i_sc/sreg_input_reg[30]} {i_sc/sreg_input_reg[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200MHz]
