set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[8]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[2]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[0]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[1]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[3]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[4]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[5]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[6]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[7]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[9]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[10]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[12]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[14]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[16]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[18]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[20]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[22]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[24]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[26]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[28]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[30]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[31]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[29]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[27]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[25]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[23]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[21]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[19]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[17]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[15]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[13]}]
set_property MARK_DEBUG true [get_nets {i_sc/sreg_input_reg[11]}]
set_property MARK_DEBUG true [get_nets sr_out_OBUF]
set_property MARK_DEBUG true [get_nets latch_IBUF]
set_property MARK_DEBUG true [get_nets sr_ck_IBUF]
set_property MARK_DEBUG true [get_nets sr_in_IBUF]
set_property MARK_DEBUG true [get_nets <const0>]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_clk_wiz/inst/clk_ec]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_sc/sreg_input_reg[0]} {i_sc/sreg_input_reg[1]} {i_sc/sreg_input_reg[2]} {i_sc/sreg_input_reg[3]} {i_sc/sreg_input_reg[4]} {i_sc/sreg_input_reg[5]} {i_sc/sreg_input_reg[6]} {i_sc/sreg_input_reg[7]} {i_sc/sreg_input_reg[8]} {i_sc/sreg_input_reg[9]} {i_sc/sreg_input_reg[10]} {i_sc/sreg_input_reg[11]} {i_sc/sreg_input_reg[12]} {i_sc/sreg_input_reg[13]} {i_sc/sreg_input_reg[14]} {i_sc/sreg_input_reg[15]} {i_sc/sreg_input_reg[16]} {i_sc/sreg_input_reg[17]} {i_sc/sreg_input_reg[18]} {i_sc/sreg_input_reg[19]} {i_sc/sreg_input_reg[20]} {i_sc/sreg_input_reg[21]} {i_sc/sreg_input_reg[22]} {i_sc/sreg_input_reg[23]} {i_sc/sreg_input_reg[24]} {i_sc/sreg_input_reg[25]} {i_sc/sreg_input_reg[26]} {i_sc/sreg_input_reg[27]} {i_sc/sreg_input_reg[28]} {i_sc/sreg_input_reg[29]} {i_sc/sreg_input_reg[30]} {i_sc/sreg_input_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list latch_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list sr_ck_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list sr_in_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list sr_out_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_ec]
